### ISSUE TITLE
It seems that HMR doesn't works

### ISSUE THREAD

**Issue by zhouchao941105** [KarlDoyle/starter-kit.angular-es6-webpack#9]
in chrome's console,it logs 'App hot update...'、'Checking for updates on the server...'、'Updated modules:'and'App is up to date.'.
But nothing changes in the page.
I just npm install and npm start.
where goes wrong?

**Comment by KarlDoyle** [comment]
@zhouchao941105 

I tried replicating but to no avail. 
I have added a gif showing hmr working from a fresh install. 

If you are still having issues, can you reopen the ticket and explain what you are aiming to modify?

![github-issue9-hmr](https://user-images.githubusercontent.com/3698173/36921765-6e0277d0-1e5d-11e8-929f-2071642ac5b5.gif)

**Comment by zhouchao941105** [comment]
Thanks for you reply.
I want HMR works without a fresh to  improve the efficiency when coding.So I want to find some solution here.
And I think changing the view with a fresh is the ability of webpack-dev-server.It can't  prove that HMR really works.
It's just my personal opinion.

**Comment by KarlDoyle** [comment]
You are indeed right, my bad.
The css is fine without reloading but angular itself is a bit tricker and requires additional work I’ll investigate further into implementing it or if you have a PR I would be happy to merge :)


Sent from my iPhone

On 3 Mar 2018, at 09:25, zhouchao941105 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for you reply.
I want HMR works without a fresh to improve the efficiency when coding.So I want to find some solution here.
And I think changing the view with a fresh is the ability of webpack-dev-server.It can't prove that HMR really works.
It's just my personal opinion.

**Comment by zhouchao941105** [comment]
Have a look at it. 
https://github.com/angular/angular.js/issues/15938
It seems that angularjs is too old to make it have HMR supported.
